INSERT INTO TODO (TODO_ID, DESCRIPTION, DONE, TARGET_DATE, USER_ID, USERNAME) VALUES (1, 'C', FALSE, CURRENT_DATE(), 1, 'adel')
INSERT INTO TODO (TODO_ID, DESCRIPTION, DONE, TARGET_DATE, USER_ID, USERNAME) VALUES (2, 'Java', FALSE, CURRENT_DATE(), 1, 'adel')
INSERT INTO TODO (TODO_ID, DESCRIPTION, DONE, TARGET_DATE, USER_ID, USERNAME) VALUES (3, 'Python', FALSE, CURRENT_DATE(), 1, 'adel')
INSERT INTO TODO (TODO_ID, DESCRIPTION, DONE, TARGET_DATE, USER_ID, USERNAME) VALUES (4, 'Php', FALSE, CURRENT_DATE(), 1, 'adel')